### ISSUE TITLE
how to translate this?

### ISSUE THREAD

**Issue by legacychimera247** [CODeRUS/screencast#7]
hello, i wanted to translate this app but didn't find any po file, how do i translate it?

**Comment by CODeRUS** [comment]
Thanks, added translations to #8, you are welcome to create pull requests for new languages

**Comment by legacychimera247** [comment]
hello and thank you, downloaded the app today, i was thinking, could you make that also the title in settings is translated?

**Comment by CODeRUS** [comment]
well, it is an app name and didn't meant to be translatable, like Miracast or so :)
